import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Brand red family sampled directly from the upGrad X logo artwork:
        // wordmark red #E41F26, the "x" gradient runs down to a deep maroon #630408.
        "outline-variant": "#f0c3c0",
        "surface-bright": "#f9f9f9",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#1b1c1c",
        "on-error-container": "#93000a",
        primary: "#e41f26",
        "secondary-container": "#e2dfde",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-container": "#fefcfc",
        "on-secondary-fixed-variant": "#474746",
        "inverse-primary": "#ffb4aa",
        "on-surface": "#1a1c1c",
        "on-secondary-fixed": "#1c1b1b",
        outline: "#a34a45",
        "inverse-on-surface": "#f1f1f1",
        "surface-container-high": "#e8e8e8",
        background: "#f9f9f9",
        "primary-fixed": "#fbdbdb",
        "tertiary-fixed": "#e3e2e2",
        "surface-variant": "#e2e2e2",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#f2a8a8",
        "on-primary-fixed-variant": "#630408",
        surface: "#f9f9f9",
        "on-primary": "#ffffff",
        "inverse-surface": "#2f3131",
        "surface-dim": "#dadada",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fffbff",
        "primary-container": "#b4151a",
        "on-surface-variant": "#603e3a",
        "surface-container-low": "#f3f3f3",
        "on-tertiary-fixed-variant": "#464747",
        "on-primary-fixed": "#3a0103",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        tertiary: "#5c5c5c",
        "on-secondary-container": "#636262",
        "tertiary-container": "#747474",
        "error-container": "#ffdad6",
        "on-background": "#1a1c1c",
        "surface-tint": "#e41f26",
        secondary: "#5f5e5e",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container": "#eeeeee",
        // Deepest tone from the logo's "x" gradient — used for 3D shadow/press states.
        "primary-deep": "#630408",
        // Legacy aliases kept for the admin panel (not covered by the Stitch handoff)
        brand: {
          red: "#e41f26",
          redDark: "#b4151a",
          redLight: "#fbdbdb",
          ink: "#1a1c1c",
          ink2: "#5f5e5e",
          gray: {
            50: "#f3f3f3",
            100: "#eeeeee",
            200: "#e2e2e2",
            300: "#dadada",
            400: "#5f5e5e",
          },
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        card: "0.5rem",
      },
      boxShadow: {
        card: "0 1px 2px rgba(20,20,20,0.06), 0 1px 1px rgba(20,20,20,0.04)",
        cardHover: "0 4px 14px rgba(20,20,20,0.10)",
      },
      spacing: {
        gutter: "16px",
        "section-gap": "32px",
        "card-padding": "16px",
        "container-margin": "24px",
        unit: "4px",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "Segoe UI", "Roboto", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "stat-lg": ["28px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
